import { Geist, Geist_Mono, Bungee } from "next/font/google";
import "./globals.css";
import Header from "@/shared/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bungeeFont = Bungee({
  variable: "--font-bungee",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="acid">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bungeeFont.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
